FROM debian:12-slim

ARG HOSTNAME=log.internal
ARG IP=192.168.0.1

USER root

RUN apt-get update && \
    apt-get -y --no-install-recommends install openssl nginx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    openssl ecparam -out /etc/nginx/graylog.key -name prime256v1 -genkey && \
    openssl req -new -x509 -nodes -key /etc/nginx/graylog.key -out /etc/nginx/graylog.crt -days 3650 -subj "/CN=Graylog Logserver" -addext "subjectAltName = DNS:${HOSTNAME},IP:127.0.0.1,IP:${IP}"

CMD ["nginx", "-g", "daemon off;"]
